Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -58,7 +58,9 @@ jobs:
           curl -sSL "https://nsfw-small.oisd.nl" | sed -e '/^[![]/d' -e '/^$/d' -e 's/||\(.*\)\^/  - '\''+.\1'\''/g' | sed '1i payload:' > rules/oisd_nsfw_small.yaml
           curl -sSL https:/ruleset.skk.moe/Clash/ip/china_ip.txt -o rules/china_ip.txt && \
           curl -sSL https:/ruleset.skk.moe/Clash/ip/china_ip_ipv6.txt | grep -v -e '^#' -e '^$' >> rules/china_ip.txt
-
+          curl -sSL "https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt" | sed -e "s#^# - #" | sed "1i payload:" > rules/apple_cn.yaml
+          curl -sSL "https://raw.githubusercontent.com/uselibrary/PCDN/main/pcdn.list" | sed -e "s#^# - #" | sed "1i payload:" > rules/pcdn.yaml
+          
       - name: Download rules (remote URLs)
         run: |
           urls=(
@@ -95,10 +97,8 @@ jobs:
 
             # Sukka / ruleset.skk.moe
             "https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt"
-            "cdn_non_ip|https://ruleset.skk.moe/Clash/non_ip/cdn.txt"
             "cdn_domainset|https://ruleset.skk.moe/Clash/domainset/cdn.txt"
             "https://ruleset.skk.moe/Clash/domainset/speedtest.txt"
-            "https://ruleset.skk.moe/Clash/domainset/download.txt"
             
             # Other
             "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/ai.list"
@@ -129,7 +129,100 @@ jobs:
             echo "Downloading $url -> rules/$filename"
             curl -L -f -o "rules/$filename" "$url" || echo "Failed: $url"
           done
-     
+
+      - name: other to yaml
+        run: |
+          urls=(
+
+            "cloudfront_ips.yaml|https://raw.githubusercontent.com/Sereinfy/ipranges/main/amazon/cloudfront_ips.txt"
+            "akamai_ips.yaml|https://raw.githubusercontent.com/Sereinfy/ipranges/main/akamai/ipv4_merged.txt"
+            "ai.yaml|https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/ai.list"
+            "cloudflare-cidr.yaml|https://raw.githubusercontent.com/sbwml/luci-app-mosdns/v5/luci-app-mosdns/root/etc/mosdns/rule/cloudflare-cidr.txt"   
+            "fake_ip_filter.yaml|https://raw.githubusercontent.com/juewuy/ShellCrash/dev/public/fake_ip_filter.list"
+            "cdn_domainset.yaml|https://ruleset.skk.moe/Clash/domainset/cdn.txt"
+            "speedtest.yaml|https://ruleset.skk.moe/Clash/domainset/speedtest.txt"
+          )
+
+          for item in "${urls[@]}"; do
+            if [[ "$item" == *"|"* ]]; then
+              # 有自定义名称
+              name="${item%%|*}"   # | 前部分
+              url="${item#*|}"     # | 后部分
+
+              # 判断 name 是否已经带扩展名
+              if [[ "$name" == *.* ]]; then
+                filename="$name"
+              else
+                ext="${url##*.}"   # 从 URL 提取扩展名
+                filename="$name.$ext"
+              fi
+            else
+              # 直接用 URL 的文件名
+              url="$item"
+              filename=$(basename "$url")
+            fi
+
+            echo "Downloading $url -> rules/$filename"
+            curl -L -f -o "rules/$filename" "$url" | sed "1i payload:" -e "s#^#  - '#;s#$#'#" || echo "Failed: $url"
+          done
+
+          for item in "${urls2[@]}"; do
+            if [[ "$item" == *"|"* ]]; then
+              # 有自定义名称
+              name="${item%%|*}"   # | 前部分
+              url="${item#*|}"     # | 后部分
+
+              # 判断 name 是否已经带扩展名
+              if [[ "$name" == *.* ]]; then
+                filename="$name"
+              else
+                ext="${url##*.}"   # 从 URL 提取扩展名
+                filename="$name.$ext"
+              fi
+            else
+              # 直接用 URL 的文件名
+              url="$item"
+              filename=$(basename "$url")
+            fi
+
+            echo "Downloading $url -> rules/$filename"
+            curl -L -f -o "rules/$filename" "$url" | sed "1i payload:" -e "s#^#  - '#;s#$#'#" || echo "Failed: $url"
+          done
+          
+      - name: Sukka to yaml
+        run: |
+          urls=(
+
+            "cloudfront_ips.yaml|https://raw.githubusercontent.com/Sereinfy/ipranges/main/amazon/cloudfront_ips.txt"
+            "akamai_ips.yaml|https://raw.githubusercontent.com/Sereinfy/ipranges/main/akamai/ipv4_merged.txt"
+            "ai.yaml|https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/ai.list"
+            "cloudflare-cidr.yaml|https://raw.githubusercontent.com/sbwml/luci-app-mosdns/v5/luci-app-mosdns/root/etc/mosdns/rule/cloudflare-cidr.txt"   
+            "fake_ip_filter.yaml|https://raw.githubusercontent.com/juewuy/ShellCrash/dev/public/fake_ip_filter.list" 
+          )
+
+          for item in "${urls[@]}"; do
+            if [[ "$item" == *"|"* ]]; then
+              # 有自定义名称
+              name="${item%%|*}"   # | 前部分
+              url="${item#*|}"     # | 后部分
+
+              # 判断 name 是否已经带扩展名
+              if [[ "$name" == *.* ]]; then
+                filename="$name"
+              else
+                ext="${url##*.}"   # 从 URL 提取扩展名
+                filename="$name.$ext"
+              fi
+            else
+              # 直接用 URL 的文件名
+              url="$item"
+              filename=$(basename "$url")
+            fi
+
+            echo "Downloading $url -> rules/$filename"
+            curl -L -f -o "rules/$filename" "$url" | sed "1i payload:" -e "s#^#- '#;s#$#'#" || echo "Failed: $url"
+          done
+          
       - name: Download and unzip `mihomo` core
         run: |
           mkdir -p tools
