Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -163,7 +163,7 @@ jobs:
             fi
 
             echo "Downloading $url -> rules/$filename"
-            if ! curl -sSL "$url" | sed -e '/^\s*#/d' -e '/^\s*$/d' -e "s/^/  - /" | sed "1i payload:" > "rules/$filename"; then echo "Failed: $url"; fi
+            if ! curl -sSL "$url" | sed -e '/^\s*#/d' -e '/^\s*$/d' -e "s/^/  - '/; s/$/'/" | sed "1i payload:" > "rules/$filename"; then echo "Failed: $url"; fi
           done
 
       - name: Download and unzip `mihomo` core
